[tox]
envlist = py311, flake8

[testenv:flake8]
basepython = python
deps = flake8
commands = flake8 src/celltraj tests

[testenv]
setenv =
    PYTHONPATH = {toxinidir}/src
deps =
    pytest
    click
commands =
    pytest --basetemp={envtmpdir}
